### ISSUE TITLE
Data generation code

### ISSUE THREAD

**Issue by cwchenwang** [POSTECH-CVLab/PeRFception#10]
Thanks for this inspiring work! I am also interested in the data generation process on CO3D and ScanNet, do you have any plans on releasing it?

**Comment by jeongyw12382** [comment]
Oh. This code is for data generation process.
If you want to generate a specific scene you desire, you could simply run the code.

You can run the code with the command below. 
`python3 -m run --ginc configs/co3d_v1.gin --scene_name [scene_name]`
`python3 -m run --ginc configs/scannet.gin --scene_name [scene_name]`

We will add more guides soon on the project page.

**Comment by cwchenwang** [comment]
Thanks for your response. May I also ask where did you use tsdf in your process since I see the tsdf code in your repo

**Comment by jeongyw12382** [comment]
@junha-l

**Comment by jeongyw12382** [comment]
We'll soon add more details about TSDF integration.
