### ISSUE TITLE
took over 70GB RAM while running 'python3 -m run --ginc configs/scannet.gin', is this a normal situation?

### ISSUE THREAD

**Issue by guijuzhejiang** [POSTECH-CVLab/PeRFception#11]
what is the minimum hardware reuirements for running this demo

**Comment by jeongyw12382** [comment]
It depends on the scene. 
Could you provide more details about your environment? 
For some scenes whose image sizes are extremely large, it could take much more memory usage. 
However, the situation you are currently on is not a normal case.

**Comment by jeongyw12382** [comment]
Closing the issue since no response is given. Please reopen the issue whenever you need help for this issue.

**Comment by Minhluu2911** [comment]
you can solve  it by set OMP_NUM_THREADS to lower value, for example:
`OMP_NUM_THREADS=1 python3 -m run --ginc configs/scannet.gin`
