### ISSUE TITLE
Downloading PeRFception-ScanNet

### ISSUE THREAD

**Issue by m13ammed** [POSTECH-CVLab/PeRFception#14]
I believe the CO3d dataset was moved from one-drive to hugging face, however, I am unable to find a working download link for the PeRFceptionScanNet. 

Can you provide a new download link? thank you in advance 

Additionally what was the estimated time to produce the PeRFception-ScanNet given your setup. Thank you again

**Comment by jeongyw12382** [comment]
Sure. 
Here is the link: https://huggingface.co/datasets/YWjimmy/PeRFception-ScanNet
We will soon add a documentation for PeRFception-ScanNet.

**Comment by jeongyw12382** [comment]
Closing the issue after offering the additional link for PeRFception-ScanNet.
