### ISSUE TITLE
Cannot download datasets with script

### ISSUE THREAD

**Issue by dataplayer12** [POSTECH-CVLab/PeRFception#8]
```Shell
python3 utils/download_perf.py --dataset co3d --outdir data/co3d/
```
exits without doing anything and looking at the script it is obvious why. Downloading chunks works as expected.

**Comment by jeongyw12382** [comment]
Oh. Sorry for the minor mistake. We have just fixed it. 
Please let me know if you have any issues regarding downloading the dataset. 
We will add the script for downloading PeRFception-ScanNet after our rebuttal is done.

**Comment by jeongyw12382** [comment]
Closing the issue after addressing the issue.
